### ISSUE TITLE
System restore deleted

### ISSUE THREAD

**Issue by LoveMeRin** [UnLovedCookie/CoutX#2]
I ran the cout optimizations with both of the settings options checked, when i went and tested it out it boosted my fps but the problem is when i use macro in the application for example roblox, it decreases my fps but 70 so like before i macro my fps are 180 but when i run the macro it drops to 80 so i went to restore point, but cout deleted all of it, i even made one restore point before the cout optimization and its gone

**Comment by UnLovedCookie** [comment]
Please make a ticket on the discord server (dsc.gg/CoutX).
