### ISSUE TITLE
Negative fps boost

### ISSUE THREAD

**Issue by dexstex6** [UnLovedCookie/CoutX#3]
Why does it reduce my fps on Fortnite
Specs
Latitude E5690
Intel Core i3 6100F
8GB DDR3-1600
AMD Radeon Vega
256GB NVMe Gen 4 SSD

**Comment by UnLovedCookie** [comment]
Have you tried the latest update?

**Comment by UnLovedCookie** [comment]
For more help, make a ticket on the discord server (dsc.gg/CoutX)
